import { DesignSystem } from "../types";

export const generateMarkdown = (ds: DesignSystem): string => {
  const { light, dark } = ds.colors;
  const comps = ds.components;

  return `
# ${ds.projectName || 'Project'} - UI Styleguide
Generated by AI

> ${ds.description}

---

## 🎨 Color Tokens

### Light Mode
| Token | Hex | Usage |
|-------|-----|-------|
| **Primary** | \`${light.primary}\` | Main Actions |
| **Primary Hover** | \`${light.primaryHover}\` | Interactive States |
| **Secondary** | \`${light.secondary}\` | Accents |
| **Surface** | \`${light.surface}\` | Cards, Modals |
| **Background** | \`${light.background}\` | Page Background |
| **Text** | \`${light.text}\` | Body Text |
| **Success** | \`${light.success}\` | Validation |
| **Warning** | \`${light.warning}\` | Alerts |
| **Error** | \`${light.error}\` | Critical Issues |
| **Info** | \`${light.info}\` | Information |

---

## 🧩 Components

### Buttons
| Type | Background | Text | Radius | Hover |
|------|------------|------|--------|-------|
| **Primary** | \`${comps.buttons.primary.background}\` | \`${comps.buttons.primary.text}\` | \`${comps.buttons.primary.radius}\` | \`${comps.buttons.primary.hover}\` |
| **Secondary** | Transparent (Border: \`${comps.buttons.secondary.border}\`) | \`${comps.buttons.secondary.text}\` | \`${comps.buttons.secondary.radius}\` | Bg: \`${comps.buttons.secondary.hoverBackground}\` |

### Cards
- **Background**: \`${comps.cards.background}\`
- **Radius**: \`${comps.cards.radius}\`
- **Shadow**: \`${comps.cards.shadow}\`
- **Hover Shadow**: \`${comps.cards.hoverShadow}\`

### Inputs
- **Background**: \`${comps.inputs.background}\`
- **Border**: \`${comps.inputs.border}\`
- **Focus Border**: \`${comps.inputs.focusBorder}\`
- **Radius**: \`${comps.inputs.radius}\`

### Badges
| Type | Background | Text |
|------|------------|------|
| **Success** | \`${comps.badges.success.background}\` | \`${comps.badges.success.text}\` |
| **Error** | \`${comps.badges.error.background}\` | \`${comps.badges.error.text}\` |
| **Warning** | \`${comps.badges.warning.background}\` | \`${comps.badges.warning.text}\` |
| **Info** | \`${comps.badges.info.background}\` | \`${comps.badges.info.text}\` |

---

## ✒️ Typography

**Font Family**: \`${ds.typography.fontFamily}\`
**Icon Style**: \`${ds.iconStyle}\`

| Scale | Size | Usage |
|-------|------|-------|
| H1 | ${ds.typography.scale.h1} | Page Titles |
| H2 | ${ds.typography.scale.h2} | Section Headers |
| H3 | ${ds.typography.scale.h3} | Sub-sections |
| Body | ${ds.typography.scale.body} | Main Content |
| Caption | ${ds.typography.scale.caption} | Small text, labels |

---

## ⚡ Motion & Spacing

**Easing**: \`${ds.animation.easing}\`

| Speed | Duration |
|-------|----------|
| Fast | \`${ds.animation.duration.fast}\` |
| Normal | \`${ds.animation.duration.normal}\` |
| Slow | \`${ds.animation.duration.slow}\` |

**Base Unit**: ${ds.spacing.base}px

---

## 💻 Developer Export (CSS)

\`\`\`css
:root {
  /* Light Mode Defaults */
  --primary: ${light.primary};
  --primary-hover: ${light.primaryHover};
  --secondary: ${light.secondary};
  --surface: ${light.surface};
  --background: ${light.background};
  --text: ${light.text};
  
  /* Functional Colors */
  --success: ${light.success};
  --warning: ${light.warning};
  --error: ${light.error};
  --info: ${light.info};

  /* Components */
  --btn-radius: ${comps.buttons.primary.radius};
  --card-radius: ${comps.cards.radius};
  --input-radius: ${comps.inputs.radius};

  /* Motion */
  --ease-default: ${ds.animation.easing};
  --duration-normal: ${ds.animation.duration.normal};
}

[data-theme='dark'] {
  --primary: ${dark.primary};
  --primary-hover: ${dark.primaryHover};
  --secondary: ${dark.secondary};
  --surface: ${dark.surface};
  --background: ${dark.background};
  --text: ${dark.text};
}
\`\`\`
  `;
};

export const downloadMarkdown = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};